<?php
/**
 * Created by PhpStorm.
 * User: root
 * Date: 12/07/2017
 * Time: 09:50
 */

namespace Namlv\Tutorial\Model\ResourceModel;


use Magento\Framework\Model\ResourceModel\Db\AbstractDb;

class Post extends AbstractDb
{
    const FILE_PATH_UPLOADED = 'namlv' . DIRECTORY_SEPARATOR . 'tutorial' . DIRECTORY_SEPARATOR . 'image' . DIRECTORY_SEPARATOR;
    const FILE_PATH_ACCESS = 'namlv/tutorial/image/';
    /**
     * @var \Magento\Framework\Stdlib\DateTime\DateTimeFactory
     */
    protected $_dateFactory;

//    public function __construct(
//        \Magento\Framework\Stdlib\DateTime\DateTimeFactory $dateFactory
//    ) {
//        $this->_dateFactory = $dateFactory;
//    }
    /**
     * Resource initialization
     *
     * @return void
     */
    protected function _construct()
    {
        $this->_init('namlv_tutorial_post', 'id');
    }

    protected function _beforeSave(\Magento\Framework\Model\AbstractModel $object)
    {
        return parent::_beforeSave($object); // TODO: Change the autogenerated stub
    }

    public function getPostStore($id)
    {
        if (!$id || ($id && (int)$id < 0)) {
            return false;
        }
        $select = $this->getConnection()->select()
            ->from(['post' => $this->getMainTable()])
            ->where('post.id =?', $id)
            ->limit(1);
        if ($result = $this->getConnection()->fetchRow($select))
            return $result;
        return false;
    }

    public function isExistPost($id)
    {
        if (!$id || ($id && (int)$id < 0)) {
            return false;
        }
        $select = $this->getConnection()->select()
            ->from(['post' => $this->getMainTable()])
            ->where('post.id =?', $id)
            ->limit(1);
        if (count($this->getConnection()->fetchAssoc($select)) > 0)
            return true;
        return false;
    }

    public function setObserver($id, $observe)
    {
        if ($this->isExistPost($id)) {

            $data = [
                "observer" => $observe
            ];
            $this->getConnection()->update($this->getMainTable(),$data,["id = ?"=> $id ]);
        }
    }
    protected function _afterSave(\Magento\Framework\Model\AbstractModel $object)
    {

        return parent::_afterSave($object); // TODO: Change the autogenerated stub
    }
}