<?php
/**
 * Created by PhpStorm.
 * User: root
 * Date: 19/07/2017
 * Time: 09:50
 */

namespace Namlv\Tutorial\Block\Adminhtml\Post\Edit\Tab;


use Magento\Backend\Block\Widget\Form\Generic;
use Magento\Backend\Block\Widget\Tab\TabInterface;
use Magento\Store\Model\Store;

class Websites extends Generic implements TabInterface
{

    /**
     * Core registry
     *
     * @var \Magento\Framework\Registry
     */
    protected $_coreRegistry;

    /**
     * @var \Magento\Store\Model\System\Store
     */
    protected $_systemStore;

    /**
     * @param \Magento\Store\Model\System\Store $systemStore
     * @param \Magento\Backend\Block\Template\Context $context
     * @param \Magento\Framework\Registry $registry
     * @param \Magento\Framework\Data\FormFactory $formFactory
     * @param array $data
     */
    public function __construct(
        \Magento\Store\Model\System\Store $systemStore,
        \Magento\Backend\Block\Template\Context $context,
        \Magento\Framework\Registry $registry,
        \Magento\Framework\Data\FormFactory $formFactory,
        array $data = []
    )
    {
        $this->_systemStore = $systemStore;
        parent::__construct($context, $registry, $formFactory, $data);
    }

    /**
     * @return void
     */
    protected function _construct()
    {
        parent::_construct();
        $this->setActive(true);
    }


    /**
     * Return Tab label
     *
     * @return string
     * @api
     */
    public function getTabLabel()
    {
        return __('Post in Websites');
        // TODO: Implement getTabLabel() method.
    }

    /**
     * Return Tab title
     *
     * @return string
     * @api
     */
    public function getTabTitle()
    {
        return $this->getTabLabel();
        // TODO: Implement getTabTitle() method.
    }

    /**
     * Can show tab in tabs
     *
     * @return boolean
     * @api
     */
    public function canShowTab()
    {
        return true;
        // TODO: Implement canShowTab() method.
    }

    /**
     * Tab is hidden
     *
     * @return boolean
     * @api
     */
    public function isHidden()
    {
        return false;
        // TODO: Implement isHidden() method.
    }

    protected function _prepareForm()
    {
        /** @var \Magento\Framework\Data\Form $form */
        $form = $this->_formFactory->create();
        $fieldSet = $form->addFieldset('base_fieldset', null);
        $this->_addElementTypes($fieldSet);
        $formData = $this->_coreRegistry->registry('namlv_tutorial_edit');
        $field = $fieldSet->addField(
            'stores',
            'multiselect',
            [
                'label' => __('Stores View'),
                'title' => __('Stores View'),
                'required' => true,
                'name' => 'stores[]',
                'values' => $this->_systemStore->getStoreValuesForForm(false, true)
            ]
        );
        $renderer = $this->getLayout()->createBlock(
            'Magento\Backend\Block\Store\Switcher\Form\Renderer\Fieldset\Element'
        );
        $field->setRenderer($renderer);
//        $formData->setSelectStores($formData->getData('stores'));
        if ($formData) {
            if ($formData->getData('stores') == null) {
                $formData->setData('stores', [Store::DEFAULT_STORE_ID]);
            }
            $form->setValues($formData->getData());
        }
        $this->setForm($form);
        return parent::_prepareForm(); // TODO: Change the autogenerated stub
    }


}