<?php
/**
 * Created by PhpStorm.
 * User: root
 * Date: 14/07/2017
 * Time: 17:07
 */

namespace Namlv\Tutorial\Block\Post;


use Magento\Framework\App\Filesystem\DirectoryList;
use Magento\Framework\Registry;
use Magento\Framework\View\Element\Template;
use Namlv\Tutorial\Model\ResourceModel\Post as PostResourceModel;
use Namlv\Tutorial\Helper\Post as Helper;
class Post extends Template
{
    private $limit;
    private $defaultNumberInpage;
    /**
     * @var \Namlv\Tutorial\Model\ResourceModel\Post
     */
    protected $_resourceModel;

    /**
     *
     * @var \Magento\Framework\App\Filesystem\DirectoryList
     */
    protected $_directoryList;

    /**
     * @var \Namlv\Tutorial\Helper\Post
     */
    protected $helper;
    private $page;
    protected $_coreRegistry;
    public function __construct(
        Registry $registry,
        Template\Context $context,
        DirectoryList $directoryList,
        PostResourceModel $resourceModel,
        Helper $helper
    ) {
        $this->_coreRegistry=$registry;
        $this->_directoryList = $directoryList;
        $this->_resourceModel = $resourceModel;
        $this->helper = $helper;
        $this->page=$registry->registry('namlv_tutorial_page');
        $this->defaultNumberInpage = $helper->getDefaultNumberInPage();
        $this->limit= isset($_SESSION['numberInPage'])?$_SESSION['numberInPage']:$this->defaultNumberInpage;

        parent::__construct($context);
    }
    protected function _prepareLayout()
    {
        $this->pageConfig->setKeywords(__('POST'));
        $this->pageConfig->getDescription(__('POST'));
        $breadcrumbBlock = $this->getLayout()->getBlock('breadcrumbs');

        $breadcrumbBlock->addCrumb(
            'home',
            [
                'label' => __('Home'),
                'title' => __('Home'),
                'link' => __('*/*/'),
            ]
        );
        $breadcrumbBlock->addCrumb(
            'post',
            [
                'label' => __('Post'),
                'title' => __('Post')
            ]
        );
        return parent::_prepareLayout(); // TODO: Change the autogenerated stub
    }
    public function getHelper(){
        return $this->helper;
    }
    public function getRootImage(){
        return '/magento/pub/media/';
    }
    public function getShortDescription($description){
        if (strlen($description) <255)
            return $description;
        else{
            $arr = explode(' ',substr($description,0,255));
            array_pop($arr);
            return implode(' ', $arr);


        }
    }

    /**
     * @return mixed
     */
    public function getPage()
    {
        return $this->page;
    }

    /**
     * @param mixed $page
     */
    public function setPage($page)
    {
        $this->page = $page;
    }

    public function getList(){
        return $this->helper->getPage((int)$this->page,$this->limit);
    }

    /**
     * @return int
     */
    public function getLimit()
    {
        return $this->limit;
    }

    /**
     * @param int $limit
     */
    public function setLimit($limit)
    {
        $this->limit = $limit;
    }

    /**
     * @return mixed
     */
    public function getDefault()
    {
        return $this->defaultNumberInpage;
    }



}