<?php
/**
 * Created by PhpStorm.
 * User: root
 * Date: 17/07/2017
 * Time: 08:49
 */

namespace Namlv\Tutorial\Block\Post;


use Magento\Framework\View\Element\Template;
use Namlv\Tutorial\Model\ResourceModel\Post as PostResourceModel;

class View extends Template
{
    /**
     * @var \Namlv\Tutorial\Model\ResourceModel\Post
     */
    protected $_resourceModel;
    /**
     * Core registry
     *
     * @var \Magento\Framework\Registry
     */
    protected $_coreRegistry;
    public function __construct(
        Template\Context $context,
        \Magento\Framework\Registry $registry,
        PostResourceModel $resourceModel
    ) {
        $this->_coreRegistry=$registry;
        $this->_resourceModel = $resourceModel;
        parent::__construct($context);
    }
    protected function _prepareLayout()
    {
        $this->pageConfig->setKeywords(__('POST'));
        $this->pageConfig->setDescription(__('VIEW'));
        $breadcrumbBlock = $this->getLayout()->getBlock('breadcrumbs');
        $breadcrumbBlock->addCrumb(
            'home',
            [
                'label' => __('Home'),
                'title' => __('Home'),
                'link' => __('*/*/'),
            ]
        );
        $breadcrumbBlock->addCrumb(
            'view',
            [
                'label' => __('View'),
                'title' => __('View'),
            ]
        );
        $data = $this->_coreRegistry->registry('namlv_tutorial_view');
        if ($data->getData('title'))
            $this->pageConfig->getTitle()->set($data->getData('title'));

        return parent::_prepareLayout(); // TODO: Change the autogenerated stub
    }
    public function getContent(){
        return $this->_coreRegistry->registry('namlv_tutorial_view')->getData('description');
    }
}